### ISSUE TITLE
Looking to collaborate

### ISSUE THREAD

**Issue by txoof** [Martenfur/magic_frame#2]
@Martenfur apologies for opening this as an issue; I tried to reach out to you on Reddit where I saw this project, but that didn't work and I couldn't find any other contact info for you.

I manage a project called [PaperPi](https://github.com/txoof/PaperPi) that makes it easy to create rotating image-based plugins across almost every single waveshare screen. [I'm currently working on adding color waveshare screens](https://github.com/txoof/PaperPi/tree/I%2379_color_display) and just about ready to move to a release.  

I would love to integrate this into PaperPi. Would you be interested incollaborating? 

Also, you may want to take a look at [epdlib](https://github.com/txoof/epdlib), a library that makes it easy to make your project resolution and screen-agnostic so it will work on any sized epaper screen.

**Comment by Martenfur** [comment]
Yeah, I got a little bit too based for reddit. :-)

I mean. You can take whatever code's here, it's free. This project's kinda one-and-done for me, I'll write the readme, make everything stable and move on. And yes, I know about the aggregator libraries, the reason I didn't use it here is because I needed to redirect some GPIO pins to different ones, because Witty Pi and the screen were using the same pins and interfering, so I needed to directly modify the drivers.

**Comment by txoof** [comment]
Cool. Thanks.

I'll take a look and see what parts I can lift into a PaperPi plugin.

**Comment by txoof** [comment]
@Martenfur last question: where did you source your frame? It looks great!
